spring:
    config:
        import: optional:configserver:http://localhost:8088
    application:
        name: study
    profiles:
        active: dev
management:
    endpoints:
        web:
            exposure:
                include: ['health', 'refresh']